using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;

public class AutoGeneratedTile : MonoBehaviour
{
    [SerializeField] int width,height;
    [SerializeField] int backgroundWidth, backgroundHeight;
    [SerializeField] int repeatNum;
    [SerializeField] GameObject tile, background;
    [SerializeField] int minHeight, maxHeight;

    void Start()
    {
        Generation();
        spawnObj(background,backgroundWidth,backgroundHeight);
    }
    //This is to generate the tiles
    void Generation()
    {
        int repeatValue = 1;
        for (int x = 0; x < width; x++)//This will help spawn a tile on the x axis
        {
         if(repeatValue == 1)
            {
                height = Random.Range(minHeight, maxHeight);
                GenerateFlatPlatform(x);
                repeatValue = repeatNum;
            }
            else
            {
                GenerateFlatPlatform(x);
                repeatValue--;
            }
        }
    }
    void GenerateFlatPlatform(int x)
    {
        for(int y = 0; y < height; y++)
        {
            spawnObj(tile, x, y);
        }
    }
    void spawnObj(GameObject obj, int x, int y)
    {
        obj = Instantiate(obj, new Vector2 (x,y), Quaternion.identity);
        obj.transform.parent = this.transform;
    }
}
